//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatedCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalculatedCard()
        {
            this.Archive = new HashSet<Archive>();
        }
    
        public int Id { get; set; }
        public int IdRegistrationCard { get; set; }
        public bool IsPayBooking { get; set; }
        public System.DateTime DateDeparture { get; set; }
        public int CountPayDay { get; set; }
        public decimal FinishPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archive> Archive { get; set; }
    }
}
