//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Number()
        {
            this.RegistrationCard = new HashSet<RegistrationCard>();
        }
    
        public int Id { get; set; }
        public int numberRoom { get; set; }
        public int IdTypeNumber { get; set; }
        public bool IsBusy { get; set; }
        public int CountRoom { get; set; }
        public int Floor { get; set; }
        public string Phone { get; set; }
        public decimal Price { get; set; }
        public bool IsBooking { get; set; }
        public int CountClient { get; set; }
        public decimal PriceOneClient { get; set; }
        public int CountFreePlace { get; set; }
    
        public virtual TypeNumber TypeNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationCard> RegistrationCard { get; set; }
    }
}
